version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MYSQL_ROOT_PASSWORD: Database@12  # Set the MySQL root password
      # MYSQL_DATABASE: your_database_name        # Optional: Create a database on startup
      # MYSQL_USER: your_user                     # Optional: Create a user
      # MYSQL_PASSWORD: your_user_password        # Optional: Set password for the user
    volumes:
      - ./usr/local-mysql-data:/var/lib/mysql      # Map local folder to MySQL data directory
    ports:
      - "1400:1433"                             # Expose MySQL port

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
   depends_on:
      - db
   ports:
      - "8080:80"
      - "8081:80"
   # restart: always
   environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development

    # build:
    #   context: ./webapp                # Path to your .NET app source code
    #   dockerfile: Dockerfile            # Name of the Dockerfile
    # ports:
    #   - "5000:80"                       # Expose the app on port 5000
    # environment:
    #   - ConnectionStrings__DefaultConnection=Server=db;Database=your_database_name;User Id=your_user;Password=your_user_password; 
    # depends_on:
    #   - db                              # Ensure db starts before webapp
